spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  freemarker:
    suffix: .ftlh
    template-loader-path: classpath:/templates/
    expose-request-attributes: true
    expose-session-attributes: true
    settings:
      template_exception_handler: rethrow

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 6MB

server:
  port: 8080
  error:
    include-message: always
    include-exception: true
  compression:
    enabled: false

# On utilise maintenant un dossier "uploads" DANS le projet
app:
  upload-dir: uploads

stripe:
  secret-key: ${STRIPE_SECRET_KEY}
  publishable-key: ${STRIPE_PUBLISHABLE_KEY}
